### ISSUE TITLE
Escaping content in class attribute doesn't work.

### ISSUE THREAD

**Issue by abishekrsrikaanth** [maizzle/framework#1026]
- Maizzle Version: latest
- Node.js Version: v20.3.0

Found an issue when using the markdown starter kit. on the main layout file here https://github.com/maizzle/starter-markdown/blob/main/src/layouts/main.html#L41, I am trying to replace the class attribute

```html
<!-- FROM   -->
class="sm:px-4 {{ page.bodyClass || 'bg-[#f1f5f9]' }}"

<!-- TO  -->
class="sm:px-4 @{{$backgroundColor}}"
```
after compiling, the output on the html file is
```html
class="sm-px-4 {{-backgroundColor}}"
```
can you please advice how to fix this? 
I also tried to replace it with
```html
class="sm:px-4 @{{$backgroundColor || 'bg-[#f1f5f9]'}}"
```
and the output was
```html
class="sm-px-4 {{-backgroundColor or-or- -bg-_f1f5f9-}}"
```

**Comment by cossssmin** [comment]
Thanks for spotting this, it's an issue with the [`safeClassNames`](https://maizzle.com/docs/transformers/safe-class-names) transformer. 

Normally you would simply redefine the [replacements mapping](https://maizzle.com/docs/transformers/safe-class-names#replacements) to keep `$` as-is, like this:

```js
// config.production.js
module.exports = {
  // ...
  safeClassNames: {
    '{': '{',
    '}': '}',
    '$': '$',
  },
}
```

However, `safeClassNames` also runs inside [Filters](https://maizzle.com/docs/transformers/filters), and the issue is that it's not using the mappings defined in your config:

https://github.com/maizzle/framework/blob/4aba7ba7547b368b0c37af921da3786c601ebd83/src/transformers/filters/index.js#L44-L55

If you're not using filters, you can just disable them and it'll work:

```js
// config.production.js
module.exports = {
  // ...
  safeClassNames: {
    '{': '{',
    '}': '}',
    '$': '$',
  },
  filters: false,
}
```

Will fix in the next release so that filters use any `safeClassNames` mappings defined in the config.

**Comment by abishekrsrikaanth** [comment]
OK, i tried the above configuration, but still have another issue I mentioned above with setting defaults.

on the layout file I have
```html
class="sm:px-4 @{{$backgroundColor || 'bg-[#f1f5f9]' }}"
```

after compilation this is the output
```html
class="sm-px-4 {{$backgroundColor or-or- -bg-_f1f5f9- }}"
```

How can I fix this?

**Comment by cossssmin** [comment]
Define the mappings for those too:

```js
// config.production.js
module.exports = {
  // ...
  safeClassNames: {
    '{': '{',
    '}': '}',
    '[': '[',
    ']': ']',
    '$': '$',
    '#': '#',
    '|': '|',
    '\'': '\'',
  },
  filters: false,
}
```

That will output ` class="{{$backgroundColor || 'bg-[#f1f5f9]' }} [] []"` - those `[]` are there because of the other arbitrary classes, which can't be cleaned up properly. For now this is as close as it gets, since the `safeClassNames` transformer does not yet support ignoring expression blocks (addded it to the backlog though).

For the other issue, can you write it with spaces inside the `{{ }}`? That would allow you to write it like this:

```html
<body class="..." {{ $backgroundColorStyle }}>
```
