### ISSUE TITLE
Maizzle api render html contains css variable

### ISSUE THREAD

**Issue by ches4117** [maizzle/framework#1120]
- Maizzle Version: 4.6.2
- Node.js Version: 18.17.1

Hello, when I use [Maizzle api](https://maizzle.com/docs/api) to render HTML having tailwind css, the generated html having css variables like below example.

```
<html>
  <head>
    <style>
      .space-x-2 > :not([hidden]) ~ :not([hidden]) {
        --tw-space-x-reverse: 0;
        margin-right: calc(0.5rem * var(--tw-space-x-reverse));
        margin-left: calc(0.5rem * calc(1 - var(--tw-space-x-reverse));
      }
      .text-stone-500 {
        --tw-text-opacity: 1;
        color: rgb(120 113 108 / var(--tw-text-opacity));
      }
    </style>
  <style>
<head>
<body>
  <div class="space-x-2 text-stone-500" />
</body>
</html>
```

This style will not render successfully in Gmail.

**Comment by cossssmin** [comment]
You need to [provide it with a config](https://maizzle.com/docs/api#tailwind) (otherwise it will use the [default one](https://maizzle.com/docs/api#default-tailwind)). 

You can use the one we have in the Starter:

https://github.com/maizzle/maizzle/blob/master/tailwind.config.js

Some utilities, like `space-x` or `divide-y` won't work in email, because they use complex selectors and CSS properties that most email clients don't support. In those cases it's better to just use margin/padding or a spacer/divider component.
