### ISSUE TITLE
Tailwind classes in conditional comments

### ISSUE THREAD

**Issue by montemartin** [maizzle/framework#133]
- Maizzle Version: 
    Framework v0.9.1
    CLI v0.5.0

### Description:
Tailwind classes applied on elements inside HTML conditional comments aren't inlined. PurgeCSS and email-comb still apply and the entire class attribute is stripped off leaving no styles on the conditionals. 

Typing out the inline styles works but severely limits the use of components. With manually entered inline values I can't use variables to apply classes that would change (e.g. bg-color, text-color, border-width, etc.). 

### Steps To Reproduce:
A production build with:
`<!--[if mso]><td class="border-white border-3 border-solid text-center w-260 h-49 mso-padding-0"><![endif]-->`

Results in: 
`<!--[if mso]><td><![endif]-->`

Expected:
`<!--[if mso]><td align="center" width="260" height="49" style="mso-padding-alt: 0; border: 3 solid #ffffff;"><![endif]-->`

**Comment by cossssmin** [comment]
Yes, it's because the inliner parses the HTML. 

As far as it's concerned, that `<td>` is a string, not an HTML tag, so it ignores it.

`email-comb` removes those classes because the inliner has `removeStyleTags: true`, which removes those classes from the `<style>`. Since they're not in there anymore, `email-comb` removes them from the HTML.

An option would be to set `removeStyleTags: false` but you can't do that currently, it's [hardcoded](https://github.com/maizzle/framework/blob/master/src/transformers/inline.js#L26). I'll make a note to make it customizable in `v1.0.0`.

`removeStyleTags: false` would prevent Juice from removing your classes, but it still wouldn't inline them. And you might think that would be enough - they'd be there and would be applied - but it won't, because Outlook on Windows only applies styles for the first class it encounters, ignoring all the rest. In your example, only `border-white` would be used by Outlook.

So this will not work as you expect in Maizzle, or in any framework that uses an inliner that parses HTML, like Juice (and I know of no inliner that doesn't do parsing). And I think this is the correct behavior, since that is just a string of text, not actual HTML.

Your only options are:

1. write inline CSS in those comments
2. when `v1.0.0` launches, update to it and use `removeStyleTags: false` to extract classes with Tailwind's `@apply`, so that you use a single class for Outlook, i.e.:

```css
/* src/assets/css/utilities.css */
.col-260 {
  @apply border-white border-3 border-solid text-center w-260 h-49;
  mso-padding-alt: 0; /* not a Tailwind utility, so we write it out... */
}
```
```html
<!--[if mso]><td class="col-260"><![endif]-->
```

Do keep in mind that `v1.0.0` will move to PostHTML and will be a breaking change, requiring I'd say small, maybe moderate time investment to migrate your existing HTML.

If it can't wait until `v1.0.0`, I'm sorry, but your only option is to write attributes and inline CSS there.

**Comment by montemartin** [comment]
`removeStyleTags: false` might work, but wouldn't that also leave ALL the tailwind classes? That would lead to some heavy code. It would probably need some type of whitelist. Can't the same thing be accomplished using the `data-embed` attribute? 

Single Outlook class-names aren't a problem for me. I use a conditional on the <html>  to set a global .mso class. With that I can easily target elements with `.mso .element-class{}`. Combined with a some customized BEM style naming it should solve the issue. Might be helpful make a note in the docs.

**Comment by cossssmin** [comment]
`removeStyleTags: false` would just leave a bit more classes in your HTML (specifically, those it did not inline). But it would not leave everything that Tailwind generates, because the bulk of the work is done by PurgeCSS, and so the CSS that the inliner receives for inlining is already mostly cleaned up.

`data-embed` on the other hand does not inline anything in the `<style>` tag it is applied to, so that is not recommended.

#### Note on PurgeCSS 

It does _not_ run when the `env` is `local`, like when running `maizzle build` or `maizzle serve` - this is on purpose, so you have all classes available in the browser dev tools (plus, it can help some editors - not vscode - with offering autocompletion). If a non-local env is specified, like when you do `maizzle build production`, it'll clean up most of the unused CSS.
