### ISSUE TITLE
Borders

### ISSUE THREAD

**Issue by sandervanhooft** [maizzle/framework#2]
Not sure whether it's me or a bug, but I can't find a solution in the docs... So posting it here. Let me know if I should move this issue.

---

Somehow I can't get the borders to show when using `class="border"` or anything border-related. I'm using the default provided (tailwind) configs.

When I run this snippet using Tailwind instead of Maizzle all works as expected though:

https://codepen.io/sandervanhooft/pen/pBzWQY

Any suggestion how I can solve this?

**Comment by sandervanhooft** [comment]
I'm trying to create this (notice the borders on the TOTAL line):

<img width="408" alt="image" src="https://user-images.githubusercontent.com/7265703/55264727-a5556880-5275-11e9-8c48-0e85528c67f5.png">

**Comment by cossssmin** [comment]
You need to define the border style, too. And border color, if you don't want it black. It works with Tailwind by default, because it includes the `base` reset - Maizzle doesn't use that.

So, with your example:

```html
<div class="p-16">
  <table class="w-full">
  <tr class="font-bold">
    <td class="py-14 border-solid border-0 border-t border-b border-gray-300">
      Total
    </td>
    <td class="text-right border-solid border-0 border-t border-b border-gray-300">
      €12.345,00
    </td>
  </tr>
  </table>
<div>
```

Need to define `border-0` first, so it doesn't add borders on the sides.

Note that this won't work as expected in Outlook: borders _will_ be added to the sides. In this case, I would suggest using a [Divider](https://maizzle.com/docs/divider/) instead.

Simply use the `<tr>` inside the Divider, adding a `colspan="2"` for your case:

```html
<div class="p-16">
  <table class="w-full">
    <tr>
      <td colspan="2" class="py-4">
        <div class="bg-gray-300 h-px leading-px">&nbsp;</div>
      </td>
    </tr>
    <tr class="font-bold">
      <td class="py-14">
        Total
      </td>
      <td class="text-right">
        €12.345,00
      </td>
    </tr>
    <tr>
      <td colspan="2" class="py-4">
        <div class="bg-gray-300 h-px leading-px">&nbsp;</div>
      </td>
    </tr>
  </table>
</div>
```

Let me know how that goes :)

**Comment by sandervanhooft** [comment]
Thanks @cossssmin, it works like a charm! I went with the dividers as you suggested, to avoid Outlook issues.
