### ISSUE TITLE
Background color is not HEX in production

### ISSUE THREAD

**Issue by pazitron1** [maizzle/framework#221]
"@maizzle/framework": "^0.6.4",
"tailwindcss-gradients": "^2.3.0"
node 10.16.1

After running maizzle build production my background colours become rgba and not hex. Same goes into bgcolor, how to set it to hex value? 

Currently:

`<table border="0" cellspacing="0" cellpadding="0" width="100%" style="--bg-opacity:1;background-color:#f3f3f3;background-color:rgba(243,243,243,var(--bg-opacity));max-width:600px;text-align:center;vertical-align:middle;width:100%" bgcolor="rgba(243, 243, 243, var(--bg-opacity))" align="center" valign="middle" role="presentation">`

Desired:
`<table border="0" cellspacing="0" cellpadding="0" width="100%" style="--bg-opacity:1;background-color:#f3f3f3;background-color:f3f3f3;max-width:600px;text-align:center;vertical-align:middle;width:100%" bgcolor="f3f3f3" align="center" valign="middle" role="presentation">`

**Comment by pazitron1** [comment]
Also, annoyingly it add --bg-opacity:1 to all my tags

**Comment by cossssmin** [comment]
It’s a feature added in Tailwind 1.4, for web dev, and it’s being used because you’re on an old version of Maizzle. 

You can either update Maizzle to the latest version (see the 1.0 release notes for the upgrade guide), or if you’d like to keep on using that you could add `target: 'ie11'` to your tailwind.config.js. 

My advice is to update Maizzle, as versions prior to 1.0 won’t get new updates.

**Comment by streetcarmarket** [comment]
@cossssmin I believe I am having a similar issue. I recently upgraded to 2.3.1 from 1.4.3, and now when I send my emails they have a white background on gmail instead of a the bg-cool-gray-900 color I have set. However, when I manually delete `background-color: rgba(26, 32, 46, var(--bg-opacity));` the bg-cool-gray-900 color shows properly on gmail. The same thing is happening to all of the colors I am using on my template, text-color, bg-color.

`<body style="margin: 0; padding: 0; width: 100%; word-break: break-word; -webkit-font-smoothing: antialiased; --bg-opacity: 1; background-color: #1a202e; background-color: rgba(26, 32, 46, var(--bg-opacity));">`

It worked perfectly when I was on 1.4.3, I don't know if I am missing something or need to make an adjustment somewhere, any help would be greatly appreciated! 

- Maizzle Version: 2.3.1
- Node.js Version: 12.16.3

**Comment by cossssmin** [comment]
Hey there, take a look at our starter's [`tailwind.config.js`](https://github.com/maizzle/maizzle/blob/71709951e5f34d64e7ad03a8ff4a0c877edb79f6/tailwind.config.js#L242-L249), we now disable all color opacity plugins specifically for this reason:

```js
corePlugins: {
  animation: false,
  backgroundOpacity: false,
  borderOpacity: false,
  divideOpacity: false,
  placeholderOpacity: false,
  textOpacity: false,
},
```

Looks like Tailwind will drop `target: 'ie11'` in v2.0 so this is going to be the way forward.
