### ISSUE TITLE
Different output between 'watch' and 'build:production' 

### ISSUE THREAD

**Issue by spekulatius** [maizzle/framework#258]
Hello @cossssmin 

thanks for Maizzle, great helper to build emails. I noticed a difference between the 'watch' and 'build:production' output in one case. To work with Laravel's Blade I've added some rather ugly code with Maizzle:

    <tr class="hover:bg-gray-300 {{ $loop->odd ? 'bg-gray-postmark-100' : '' }}">

In case of 'watch' it works as expected and puts the $loop variable out. In the build it doesn't and outputs:

    <tr class="hover-bg-gray-300 {{ $\> ?'bg-gray-postmark-100' - '' }}">

Maybe you got any idea how I can get to print out the $loop correctly?

- Maizzle Version:

```
$ maizzle -v
Framework v1.3.0
CLI v1.0.2
```

- Node.js Version:

```
$ node -v
v10.18.1
```

Cheers!

**Comment by cossssmin** [comment]
Use `@{{ }}` as you would with Blade, Maizzle also supports ignoring `{{ }}` with an `@` in front:

```
<tr class="hover:bg-gray-300 @{{ $loop->odd ? 'bg-gray-postmark-100' : '' }}">
```

Docs: https://maizzle.com/docs/templates/#curly-brace-conflicts

**Comment by spekulatius** [comment]
Hello @cossssmin 

awesome, thank you for pointing me in the right direction. I didn't see this before 👍️

Cheers,
Peter

**Comment by spekulatius** [comment]
Oh, I probably was a bit too quick and didn't check it proper. It looks like neigther `@{{ }}` nor `<raw>` are working in my case. I still get the broken output:

```
{{ $> ?'bg-gray-postmark-lighter' - '' }}
```

Either with an `@` or with `<>` in front (depending on the solution used). Is this maybe caused by the check being part of an attribute @cossssmin ?

**Comment by cossssmin** [comment]
Thanks, found the issue.

It's an unfortunate combination of [`safe-class-names`](https://maizzle.com/docs/code-cleanup/#safeclassnames) and [`email-comb`](https://maizzle.com/docs/code-cleanup/#removeunusedcss). 

`safe-class-names` replaces `:` with a `-`, screwing up the second part of a ternary operator. This needs to be handled in [posthtml-safe-class-names](https://github.com/posthtml/posthtml-safe-class-names).

`email-comb` on the other hand, removes the `loop` word (or any word you replace it with, because it thinks it's a class name. Not sure how to best handle this, so for now you could: 

1. [disable the cleanup transformer](https://maizzle.com/docs/code-cleanup/#enabled)
2. [disabled safe-class-names transformer](https://maizzle.com/docs/code-cleanup/#safeclassnames)

This will work, but CSS class names won't be unescaped properly and you'll notice some of them not working in email clients such as Gmail. You could probably run safe-class-names after everything is done, for example in the [afterTransformers](https://maizzle.com/docs/events/#aftertransformers) event:

```js
events: {
  afterTransformers (html, config) {
    const posthtml = require('./node_modules/posthtml')
    const safeClassNames = require('./node_modules/@maizzle/framework/node_modules/posthtml-safe-class-names')

    return posthtml([safeClassNames()]).process(html).then(result => result.html)
  }
}
```

... though that would still leave the `:` part of the ternary screwed up... Need to handle this in the `posthtml-safe-class-names` plugin itself, somehow...

**Comment by spekulatius** [comment]
Hello @cossssmin 

Thanks for checking the problem further! Interesting to see a bit more of the 'inner works' of Maizzle. 

After trying a few things out I've opted to go with a split of the operator into different tags:

    @if ($loop->odd) 
    <tr class="hover:bg-gray-postmark-light bg-gray-postmark-lightest">
    @else
    <tr class="hover:bg-gray-postmark-light">
    @endif

A fairly ugly approach, but it works for both `build:production` and `watch`.

Cheers,
Peter

**Comment by spekulatius** [comment]
Hello @cossssmin again,

haha, I'm sorry to return with the same topic once more. I've noticed another difference in the way it behaves using my work-around mentioned above. When compiling the email template it works in the preview in the browser fine (for both `build:production` and `watch`). But when sent to my gmail address I get a broken table. After some researching I've noticed an additional closing tag for the `tr` being added during the build steps:

```
@if ($loop->odd)
  <tr class="hover-bg-gray-postmark-light" style="background-color: #f4f4f7;" bgcolor="#f4f4f7">
@else
  </tr>
  <tr class="hover-bg-gray-postmark-light">
@endif
```

In tthe regular browser view it seems to be fixed by FF, while in gmail it isn't fixed anymore. I guess there is some fixing of apparently broken HTML going on in the background. Am I right with this guess?

Cheers,
Peter
