### ISSUE TITLE
What does the build do? Can I NOT run it?

### ISSUE THREAD

**Issue by yellow1912** [maizzle/framework#353]
Hello,

Thank you for Maizzle. This is a more generic question but I think it's applicable to many people that may use Maizzle.

I plan to use tailwind css for our newsletter email builder, I'm considering Maizzle but I have several questions/concerns:

The situation:
We use a builder to allow users to kind of drag and drop the email template. The end result will be an optimized tailwind-based html. For that reason, we probably won't need things such as extra-attributes, base-image-url, url-parameters,....

We store these templates as nested tree of widgets, each widget will contain template code (twig) and some data providers. To get the complete html we will have to render the widgets first. Since these emails belong to a bigger campaign by the users, each email will be sent out thousands, hundreds of thousands of time. However, each email is still slightly different (sometimes different greeting text, sometimes perhaps a different list of personalized products suggested)

Do we have to build for each email html in this case? It can be a huge time blocker in our system (not to mention the surge of resources requirement)

**Comment by cossssmin** [comment]
So if I understood correctly, you could probably compile the template just once, as long as you don't use the config in Maizzle for rendering recipient-specific data like user names or greetings.

I understand you'd just need to compile an HTML email that has been styled with Tailwind CSS, so that it renders with inlined CSS and unused CSS removed, right? 

In this case, the [default production config](https://github.com/maizzle/maizzle/blob/master/config.production.js) has you covered - just make sure to not use any recipient-specific data/variables in the template. So you'd get an HTML string that you can feed into your ESP and have _it_ replace variables like `{{ user.name }}` or what have you (see [docs for escaping expressions](https://maizzle.com/docs/templates/#escaping)).

If you need to compile Maizzle in your Node app, see the [render()](https://maizzle.com/docs/nodejs/) method instead of using the CLI tool.

**Comment by cossssmin** [comment]
Feel free to reopen if you need to 👍
