### ISSUE TITLE
Box Shadow not working correctly in 3.0

### ISSUE THREAD

**Issue by chasegiunta** [maizzle/framework#376]
I'm aware that the plugins where CSS variables are required are disabled by default. Since Tailwind 2.0, box shadows are utilizing these variables. Is it possible that they are usable, despite not working in all email clients? Currently, even if I explicitly declare plugin enabled, box shadows are not working properly.

As a workaround, I know I can override box shadows in my tailwind config using the Tailwind 1.9 values, but just raising this as a potential concern.

- Maizzle Version: 3.0.1
- Node.js Version: 14.12.0

**Comment by cossssmin** [comment]
We're preventing `--tw-shadow` from being inlined on virtually every element:

https://github.com/maizzle/framework/blob/54b47be1164efcbfebf9c68978d5a62aa71eded5/src/transformers/inline.js#L17-L21

Since that variable is defined for all elements ([see discussion](https://github.com/tailwindlabs/tailwindcss/discussions/2813)), excluding it there was the only way to stop seeing it inlined everywhere. So right now, even if you were to [define `excludedProperties`](https://maizzle.com/docs/css-inlining/#excludedproperties), the variable would still be discarded when inlining.

1. One option would be to [disable CSS inlining](https://maizzle.com/docs/css-inlining/#enabled), but that _will_ cause issues in Outlook 2007-2019 on Windows (it only applies the first class in a `class=""` attribute, so `class="text-red-100 font-bold"` won't be bold). It will also cause issues in email clients that don't support CSS in a `<style>` tag in the `<head>`. And very likely when an email is forwarded.

2. Another option would be to add it in a `<style>` tag for which you [prevent CSS inlining](https://maizzle.com/docs/css-inlining/#prevent-inlining). 

    For example, in a template:

    ```html
    <extends src="src/layouts/master.html">
      <block name="head">
        <style data-embed>
          * {
            --tw-shadow: 0 0 #0000;
          }
        </style>
      </block>
      <block name="template"> 
        your template markup... 
      </block>
    </extends>
    ```

    That will add a new `<style>` tag after the main one in the compiled HTML.

3. Yet another option would be for you to add it to a `@media` query in one of the CSS files, i.e. in `reset.css`:

    ```diff
    /* src/assets/css/custom/reset.css */

    body {
      @apply m-0 p-0 w-full;
      word-break: break-word;
      -webkit-font-smoothing: antialiased;
    }

    img {
      border: 0;
      @apply max-w-full leading-full align-middle;
    }

    + @media screen {
    +   * {
    +     --tw-shadow: 0 0 #0000;
    +   }
    + }
    ```

    CSS in `@media` queries doesn't get inlined, and everywhere CSS variables are supported, `@media` queries are supported as well.

---

I'm not sure it's a good idea to allow overriding `excludedProperties` - if a user needs to prevent inlining some CSS property, they'd need to also manually add `--tw-shadow` to the list... same with all the `ring` variables...

Maybe these CSS variables resets could sit inside a `@media` query in Tailwind itself, so CSS inliners would ignore it (I've [asked](https://github.com/tailwindlabs/tailwindcss/discussions/2813#discussioncomment-138331) Adam about it, let's see what he thinks).

**Comment by chasegiunta** [comment]
Thanks @cossssmin, this is probably a user-error on my part (I'm still not up to speed on CSS variable usage), but after attempting to implement your workarounds, I'm still not able to get shadows.
<img src="https://user-images.githubusercontent.com/1377169/100274098-7b10ee00-2f23-11eb-91fb-bbdcafa3bbe2.png" width="500px">

Compare this with Tailwind ootb:

<img src="https://user-images.githubusercontent.com/1377169/100274267-be6b5c80-2f23-11eb-842d-bfdac4fcb4bf.png" width="500px">

Are the actual box-shadow values being omitted?

**Comment by chasegiunta** [comment]
Apologies, this looks to be because inlineCss was enabled.
