### ISSUE TITLE
Global variables undefined in nested components inside loops (worked well previously)

### ISSUE THREAD

**Issue by schirliuradu** [maizzle/framework#397]
- Maizzle Version: 3.1.4
- Node.js Version: 14.15.1

Hi @cossssmin,

I have a particular use case in which i have to loop an array, and inside each loop i instantiate some components. Inside those components i use the current loop item variable to access all data i need. It was possibile to do that until 3.1. 

Wanted to know if this is just a small bug or it is a wanted behaviour? 

For a serious use of maizzle where you have big components made by many nested components, i think it would be super important to have this feature. The alternative would be to have the possibility to pass all that item as a prop (in locals object) but you know we can't do that, because it would not be a valid json object. 

Have you considered this case? What would be the solution for a case like this? 

I'll leave [here](https://github.com/schirliuradu/maizzle-nested-components-loop) a link to a very small example that is reproducing this error, just to help you to understand better the use case. This is a dummy example, but in my case i have big templates and nested components and nested loops and i really need that feature, that's why i'm asking. 

By the way, i've noticed that now we can use global variables (coming from page object) and pass also locals object. This is super powerful and nice. I really hope it has nothing to do with this issue, and that i will still be able to use this feature in my next email templates with maizzle :).

**Comment by cossssmin** [comment]
> I really hope it has nothing to do with this issue

It does, and 3.1.4 screwed this up good 🤦‍♂️

For now the only option is to downgrade, sorry...

**Comment by cossssmin** [comment]
An alternative is to use the loop inside the component, that'll work.

**Comment by cossssmin** [comment]
Opened https://github.com/posthtml/posthtml-modules/issues/64, but I woudn't hold my breath... :)

Since adding support for global and local attribute variables to work together, `posthtml-modules` now returns a string that is basically HTML with expressions compiled. 

It used to return an empty object when the `locals=""` attribute was missing, which is why it was working (and why it failed when you _did_ provide the attribute). And although in most cases it shouldn't have worked, this is one case where you'd expect it to cascade down into the component and just work.

I understand that components in Maizzle might be viewed as similar to how you'd use them in a web framework like Vue or React, where you pass props - and I'd love it to be true - but the reality is that 1) we use a much simpler compilation strategy, 2) we're nowhere near that level and 3) we could use all the help we can get 🙂

**Comment by cossssmin** [comment]
@schirliuradu with the latest 4.x alpha, given your example project, you can do something like this:

```js
const items = [
  {
    title: 'lorem',
  },
  {
    title: 'lorem ipsum',
  },
]
```

#### parent.html

```html
<each loop="item, key in items">
  <component
    src="example.html"
    item="{{ item }}"
  ></component>
</each>
```

#### example.html

```html
{{{ JSON.parse(item).title }}}
```

#### Result

```html
lorem
lorem ipsum
```

Of course, that `{{{ JSON.parse(item).title }}}` can be extracted to a method that you add in the config, so it doesn't look so verbose. Give it a try and let me know what you think.

**Comment by schirliuradu** [comment]
Hi @cossssmin,

Sorry for the delay of my answer. I was trying the solution above, and it works. It seems to be fine.

There is only a small issue, if there is a string containing the `'` in the object you pass down to the children component. It seems that it does some transformations during that step which truncates all the part of the string which, the part after the `'` char. Do you have any ideas on that? 

This one could be an example:

```
const items = [
  {
    title: "lorem ipsum dol'or sit amet",
  }
]
```
