### ISSUE TITLE
Cannot ignore curly braces in front matter string

### ISSUE THREAD

**Issue by viperfx** [maizzle/framework#419]
```
---
title: "Join <raw>{{admin_name}}</raw>"
preheader: "Join @{{admin_name}} "
---

```

Expected behavior: The curly braces should be ignored. 
What happens: When the template is built the template replaces this variable with "undefined"

The above options do not work - this is inconsistent with what's expected as a syntax in the template.

**Comment by cossssmin** [comment]
Use a double `@` for now, we'll update the docs if it can't be fixed to work in one pass:

```
---
preheader: "Join @@{{admin_name}} "
---
```

`<raw>` won't work, only expressions are supported in front matter.

**Comment by viperfx** [comment]
@cossssmin Double `@@` does not work for me. After building it still outputs `undefined`

**Comment by cossssmin** [comment]
Where are you using `{{ page.title }}` and `{{ page.preheader }}`? 

If it's just the ones from the default starter layout, looks like they'll need to be escaped, i.e.:

```html
<if condition="page.title">
  <title>@{{ page.title }}</title>
</if>
```

```html
<if condition="page.preheader">
    <div class="hidden text-0 leading-0">@{{ page.preheader }}</div>
  </if>
```

Otherwise escaping with a single `@` like `title: @{{admin_name}}` and using `{{ page.title }}` seems to work fine.

Not sure whether that's a bug with how Maizzle uses PostHTML plugins or an issue with `posthtml-expressions` itself, will look into it and either try to fix it or mention the gotcha in the docs.

**Comment by viperfx** [comment]
Okay that works! Yes - I needed to escape on the layout too, But works with a single @ applied to both places.

**Comment by cossssmin** [comment]
Right, so this happens because expressions in this case are evaluated twice:

1. in Front Matter
2. in the Template/Layout

So you need to escape it once in the Front Matter and once in the layout.

In the Template's Front Matter:

```
---
preheader: "Join @{{admin_name}} "
---
```

In the Layout:

```html
<if condition="page.title">
 <title>@{{ page.title }}</title>
</if>
```

It's a gotcha of how Maizzle works to enable expressions in FM, I've [documented](https://maizzle.com/docs/templates/#ignoring-expressions-inside-front-matter) it.

**Comment by viperfx** [comment]
@cossssmin ive come across another issue where I cannot escape variables that are include via a component

**Comment by viperfx** [comment]
Also postmark uses three curly braces for allowing dynamic content such as HTML. Is there a way we can escape so it renders like `{{{ content }}}`

**Comment by cossssmin** [comment]
> @cossssmin ive come across another issue where I cannot escape variables that are include via a component

Just tested and it works fine, can you provide an example where it fails?

> Also postmark uses three curly braces for allowing dynamic content such as HTML. Is there a way we can escape so it

You can theoretically escape `{{{ content }}}` with `@{{{ content }}}`, but it looks like it's not working as expected in `posthtml-expressions`. Got it working with `{@{{ content }}}` (I know it's weird but it'll have to do until we get it fixed). `<raw>{{{ content }}}</raw>` should also work.

**Comment by darren-toha** [comment]
Hi @cossssmin, I've run into the same issue on our project, even when using the `@{{var}}` syntax in both the template and Front Matter:

We're using `"@maizzle/framework": "^3.0.0"`

_main.html_
```
  <if condition="page.title">
    <title>@{{ page.title }}</title>
  </if>
```
 

_template.html > extends main.html_
```
---
title: Awesome! You've achieved @{{achievement}}
---
```

_compiled.html_

`<title>Awesome! You&#039;ve achieved undefined</title>`

Any help would be appreciated. Thanks
