### ISSUE TITLE
Prevent baseImageURL being prepended to absolute src URLs

### ISSUE THREAD

**Issue by q-state** [maizzle/framework#559]
- Maizzle Version: 3.7.2
- Node.js Version: 14.16.1

Is there a way to prevent the `baseImageURL` value being prepended to absolute URLs in src attributes? Seems odd that it would be doing this.

Makes sense that when the email is deployed images with src values such as `/images/logo.png` would need to be hosted somewhere, and that host location be configured globally, but not when src is something like `https://images.mycdn.com/logo.png`.

**Comment by cossssmin** [comment]
There's no way to do that currently, no. `baseImageURL` is naive and just takes your string and prepends it to the `src`/`srcset`. A temporary workaround would be to maybe use something like `data-src` attributes for absolute URLs, and rewrite that to just `src` with [replaceStrings](https://maizzle.com/docs/code-cleanup/#replacestrings) (downside being you won't see images when developing locally).

I think we should move the implementation to a PostHTML plugin instead of the regex we use right now. This will also make it easier to add options like maybe safelisting/blocklisting certain types of URLs.

Will add it to the list, it'll most likely be ready in the next major version together with Tailwind 3 and other goodies 👍

**Comment by cossssmin** [comment]
Working on the plugin here: https://github.com/posthtml/posthtml-base-url

It's almost ready to go and will be available starting with Maizzle 4.0. 

VML background images will still be handled with a regex, see my comment here: https://github.com/maizzle/framework/issues/546#issuecomment-991652366

**Comment by cossssmin** [comment]
Should be fixed in `v4.0.0-alpha.1`, feel free to reopen if it isn't 👍
