### ISSUE TITLE
Tailwind CSS v3 released 🎉

### ISSUE THREAD

**Issue by spridev** [maizzle/framework#579]
- Maizzle Version: any
- Node.js Version: any

[Tailwind CSS](https://www.npmjs.com/package/tailwindcss) 3.0 has recently been released. The [Upgrade Guide](https://tailwindcss.com/docs/upgrade-guide) should be a good starting point to update Maizzle.

**Comment by cossssmin** [comment]
Yup, it'll come in Maizzle 4.0 since it will introduce breaking changes for some users 🙂

Already have it working in the PR (https://github.com/maizzle/framework/pull/575), we just need to take the time and add the rest of the [features and fixes for 4.0](https://github.com/orgs/maizzle/projects/3).
