### ISSUE TITLE
Hot reload when editing imported Markdown

### ISSUE THREAD

**Issue by robert-jelenic** [maizzle/framework#590]
- Maizzle Version: v3.7.2
- Node.js Version: v12.16.3

Is it possible to hot reload the localhost server preview when a loaded external MD file is edited? Right now, I need to restart the server on every edit. I'm using the guidance from these docs: https://maizzle.com/docs/markdown/#importing-files

**Comment by cossssmin** [comment]
Try adding the path to your .md files directory to Browsersync's `watch`. Paths there will be added to the ones Maizzle watches by default, so when a files is updated a full rebuild should be triggered.

https://maizzle.com/docs/build-config/#watch

```js
module.exports = {
  build: {
    browsersync: {
      watch: [
        './markdown',
        'content/example.md'
      ]
    }
  }
}
```

**Comment by robert-jelenic** [comment]
Hi @cossssmin, thanks for the quick reply! Truth be told, the MD file that the template is referencing is in the exact same directory as the template HTML file. So I shouldn't really need to additionally explicitly specify that in the config...but I did anyway, right down to the individual document level (eg. src/templates/directory/content.md). In the terminal, I can see that the change in the file was recognized, but no new index.html file is being rendered in build_local, and therefore no new version is loading in the browser.

`✔ Compiled in 0.654s [src/templates/template_directory/content.md]`

Strangely, a new HTML file is being generated in build_local, identically named as the MD file is named but with an HTML file extension. The content of that file is identical to content.md.

**Comment by cossssmin** [comment]
I'll have to play around with it a little, I can see why it logs that confusing message that it compiled the `.md` file when in fact it shouldn't (and it actually doesn't _compile_ it, it just copies it over to the dist folder).

Looking at [how we rebuild watched files](https://github.com/maizzle/framework/blob/a0e41c0ba104f925ceda02192f5bb5f90785638e/src/index.js#L69), I realize we don't restrict (re)compiling to only files that are defined as template sources _and_ that have the [`fileTypes`](https://maizzle.com/docs/build-config/#filetypes) we have configured.

**Comment by robert-jelenic** [comment]
Thanks! And I know this is an open-source initiative so I have no expectations on timeline or such. Just flagging things to make it better. I love the framework!

**Comment by cossssmin** [comment]
Sorry for the delay in getting back to this, just had another look with alpha8 and given this template that imports the starter's readme:

```html
<extends src="src/layouts/main.html">
  <block name="template">
    <md src="./README.md">
      # You'll see contents of README.md above this heading
    </md>
  </block>
</extends>
```

... it works with this config:

```js
module.exports = {
  build: {
    browsersync: {
      watch: [
        './*.md'
      ]
    },
	// ...
  },
}
```

It won't work when you have the `.md` file in the same folder as your templates (or in any `build.templates.source` folder). 

What happens is that Browsersync watches the path you have the `.md` file in, and will try to trigger a single file rebuild because it doesn't check if the file extension against the allowed `build.templates.filetypes` list. That's why you see `✔ Compiled in 0.654s [src/templates/template_directory/content.md]` in the console, it thinks it's a template file. 

However when Maizzle receives the request to compile your `.md` file to a `.html` file, it will not do it because it will only parse whatever file extensions you've set in [`build.templates.filetypes`](https://maizzle.com/docs/build-config/#filetypes) (default is just `html`). To test this, simply update your templates config to look like this and you'll see `README.html` output in `build_local`:

```js
templates: {
  source: 'src/templates',
  filetypes: ['html', 'md'],
  // ...
}
```

I'll add a fix for Browsersync so that it doesn't log that confusing message that it compiled `content.md` to the console and that it doesn't request a template compilation that won't run.

Unfortunately, since we can't add the template sources to the 'global paths' watched by Browsersync (that would work because it would rebuild _all_ templates, just like doing `maizzle build`, but would compile all templates first, and then just the template you've saved), the only solution is to not keep that markdown file in a templates source folder, and add it (or the entire folder it lives in) to the watched paths, as in my example above.

**Comment by cossssmin** [comment]
> I'll add a fix for Browsersync so that it doesn't log that confusing message that it compiled content.md to the console and that it doesn't request a template compilation that won't run.

Added in 44a98640891c5e691f280d1e9b4d11d2de36f19d

**Comment by cossssmin** [comment]
Thanks Robert, it was a long time coming... :)
