### ISSUE TITLE
Some kind of caching issue?

### ISSUE THREAD

**Issue by Joobs** [maizzle/framework#61]
- Maizzle Version: 0.4.3
- Node.js Version: 10.16.0

I'm using a system with a lot of includes. I've not quite figured out how to replicate, but I will update my ticket when I have a moment. I'm experiencing this on two different instances/projects.

After I run a build task (staging or production), I often experience two issues:

Changes in the HTML have not been picked up. I often have to add random text and rerun the build.  For example I commented out a chunk of text and replaced it with an include, when I ran the build the uncommented text appeared (as if it was serving a cached version of that include) and the new include appeared.
Tailwind classes get removed and are not inlined. If the tailwind class has been used before, it get's inlined.  If it's the first time I've used the class it's ignored and removed. If I add the class to the base template it's then parsed correctly in the includes.

The issues seem to be happening in the included templates.

**Comment by cossssmin** [comment]
Are you able to share a repo so I can look into it? 

Maizzle [configures Nunjucks](https://github.com/maizzle/framework/blob/master/src/nunjucks/index.js#L7) to _not_ cache templates, but maybe there's something else at play here.

Regarding Tailwind classes in includes, if you have custom includes folders make sure they are specificed in the `cleanup` config so that `purgeCSS` doesn't remove them - see the [docs](https://maizzle.com/docs/tailwindcss/#css-purging).

**Comment by Joobs** [comment]
Thanks - It was a custom include folder and I didn't see that part of the docs. That has solved the Tailwind classes issue.

The "caching" was an intermittent issue, and I think it was only happening on templates in the custom folder.
I'll open a more detailed ticket if it still happens and try and figure out the steps to recreate.
