### ISSUE TITLE
Dark Mode as Tailwind class support

### ISSUE THREAD

**Issue by rabberbock** [maizzle/framework#619]
- Maizzle Version: 4.0.0-alpha.1
- Node.js Version: 16.13.0

Is there support for using Dark Mode as a class? I see in the templates you use a screen with:
```
dark: {raw: '(prefers-color-scheme: dark)' }
```
Our use case would be to get a user setting from the database to determine light or dark mode instead basing it off of the `prefers-color-scheme`. Tailwind allows this through the `darkMode: "class"`, but it seems that the generated Maizzle code does not take effect.

Thanks!

**Comment by cossssmin** [comment]
Just tested and it works fine, are you adding the `dark` class to a parent element?

```html
<div class="dark">
  <div class="bg-white dark:bg-slate-800">Example</div>
</div>
```

```js
// tailwind.config.js
module.exports = {
  darkMode: 'class',
  // ...
}
```

> I see in the templates you use a screen with:

That's for the `media` query strategy, it was useful when Tailwind added each utility in its own `@media` block so instead of getting 5 media queries for 5 utilities with that you'd use a screen and just get one. Don't think it's needed anymore.

**Comment by rabberbock** [comment]
@cossssmin Looks like I had some old configuration that generated the dark mode into the `prefers-color-scheme`. Works great! Thanks!
