### ISSUE TITLE
`<outlook>` tag doesn't work when nested

### ISSUE THREAD

**Issue by jebax** [maizzle/framework#660]
- Maizzle Version: 3.7.3
- Node.js Version: 14.7.3

Hi,

When I have an `<outlook>` or `<not-outlook>` tag that's nested inside another one, it doesn't compile to the relevant HTML comments when used with `Maizzle.render()` - it just gets outputted as `<outlook>`.

My use case for nested `<outlook>` tags is to have them inside my template to change its styling, then also using the tag inside a reusable component (e.g. a footer) which is rendered in both outlook and non-outlook versions of the template.

Thanks!

**Comment by cossssmin** [comment]
Nesting `<outlook>` tags is not supported, so something like this will not work:

```html
<outlook>
  test
  <outlook>test 2</outlook>
</outlook>
```

If it worked, that woud compile to:

```
<!--[if mso]>
  test
  <!--[if mso]>test<![endif]-->
<![endif]-->
```

While that doesn't look like a big deal and would possibly still work, nesting `<outlook>` in `<not-outlook>` or vice-versa would make no sense and wouldn't even work.

Can you share an example of what you're doing? Maybe there's another way to do it.

**Comment by cossssmin** [comment]
Yeah in general I'd recommend using separate components, it's good practice that you don't mix concerns especially for when you need to get back to that code weeks or months later. Instead of having one 'dynamic' component that renders tables or divs based on a conditional, have two dedicated components that have clear purpose. Easier to understand when returning to a project or wanting to reuse them in a different one.

But in your example, assuming your Outlook button contains VML code, you could have everything inside the button component and, instead of nesting `<outlook>` tags you'd just write out the code in full:

```html
<!-- button.html -->
<not-outlook>
  <div class="some non-outlook-compatible CSS">
    <a href="">button for modern clients</a>
  </div>
</not-outlook>
<outlook>
  <div class="some outlook-compatible CSS">
    <!-- VML/'bulletproof' button -->
    <!--[if mso]>
      ...
    <![endif]-->
  </div>
</outlook>
```
