### ISSUE TITLE
Six-digit HEX transformer applies to text content

### ISSUE THREAD

**Issue by hteumeuleu** [maizzle/framework#668]
- Maizzle Version: 3.7.3
- Node.js Version: 15.14.0

The [Six-digit HEX](https://maizzle.com/docs/code-cleanup/#six-digit-hex) transformer erroneously applies to text content inside HTML. For example, inside a template, the following content:

```
<h1>Welcome to issue #123 or our newsletter!</h1>
```

…is turned into:

```
<h1>Welcome to issue #112233 or our newsletter!</h1>
```

Setting `sixHex:false` in the config solves this (but turns this off which might be unfortunate for those who need it).

**Comment by cossssmin** [comment]
Ah, bummer! We'll need to port this plugin to a PostHTML plugin that only looks inside predefined places (like `style` attributes and tags), since the original [color-shorthand-hex-to-six-digit](https://codsen.com/os/color-shorthand-hex-to-six-digit/) is not concerned with this and applies to the entire HTML string.

As a temporary solution, you can use something like `&num;` instead of the `#`, i.e. `&num;123`.

Thanks for catching this!

**Comment by hteumeuleu** [comment]
You're welcome! Yes, I thought about using a special character like a `&zwnj;` as well. 

Also, note that six digit hex is a thing only for HTML attributes (like `bgcolor`or `color`). That's per specification (famously explained by the [Why does HTML think “chucknorris” is a color?](https://stackoverflow.com/questions/8318911/why-does-html-think-chucknorris-is-a-color) post). As far as I know, every email client (yes, even The Outlooks on Windows) have great support for 3 digit hex colors in CSS.

**Comment by cossssmin** [comment]
Cool, will keep that in mind when refactoring the transformer 👍
