### ISSUE TITLE
Maizzle doesn't convert grid code to tables?

### ISSUE THREAD

**Issue by sparker888** [maizzle/framework#682]
👋 New user here. I don't know where else to send this. So, I tinkered around with Maizzle for the first time setting up a campaign for a client. I really love it! One thing I was surprised about though was that the processor spit out grid-based css styles when Google Mail doesn't support them. Am I missing something? Perhaps I can help/contribute. Thx!

**Comment by cossssmin** [comment]
Hi there, welcome 👋

Maizzle works differently, as in it doesn't expand code into table structures - you need to write the markup yourself. The only processing done on the Tailwind CSS utility classes are inlining and rewriting escaped characters to 'safe' ones (Gmail drops your entire style tag if you have classes like `w-1\/2`).

At the moment there are no plans to support something like this but... never say never, right? :)

**Comment by cossssmin** [comment]
Yeah, we try to do as much as possible to get Tailwind 🤝 HTML email, like making sure some resets aren't inlined all over the place, providing plugins to make it easier to style/target email clients etc. Conversion of `grid` classes to table markup would probably be pretty hard to get right, like for example in which column would you place the text?

```html
<div class="grid grid-cols-2">
  text
</div>
```

Lots of room for user error, easy to get unexpected results that might even be hard to catch in CI etc.

Something like this:

```html
<row cols="2">
  <col span="1">first</col>
  <col span="2">second</col>
</row>
```

... might be better and I think it's possible through a custom PostHTML plugin, which is why I'm not ruling out the possibility. 

It'd be very similar to MJML/Foundation for Emails, and the biggest downside here is that we'd become responsible for testing/maintaining the table-based markup that it would generate. Could be avoided through user-defined tag expansions, i.e.:

```js
{
  row: '<table><tr><td>$content</td></tr></table>'
}
```

🤔
