### ISSUE TITLE
Minify with html-crush lineLengthLimit: 500 doesn't actually limit lines to 500

### ISSUE THREAD

**Issue by bravecrayon** [maizzle/framework#742]
- Maizzle Version: 4.0.2
- Node.js Version: 14.19.3

Config used (from the docs):
```
minify: {
  lineLengthLimit: 500,
  removeIndentations: true,
  breakToTheLeftOf: [],
}
```

In the one email I'm working on, the longest line ends up being 715 characters. If I remove autoprefixer plugin, it shortens to 681 characters. This makes it seem like html-crush is being run before other plugins instead of last — and I would guess it should be last.

Edit: It seems like maybe `breakToTheLeftOf` maybe the culprit. Removing that helps keep everything under 500.

**Comment by cossssmin** [comment]
Yeah, the way minification works it probably never can be exactly 500 chars long in real life, because many times there's a string of text it simply can't break onto a new line.

Setting `breakToTheLeftOf: []` should basically say "don't add a new line before any tag", [according to the docs](https://www.codsen.com/os/html-crush/#api---crush) (it disables the default list). However it'll still inline because the rest of the options still take effect. And when it does, it just uses those defaults which don't cover many tags.

We could improve this by automatically including these in the default list, with an option for you to still override it completely:

```js
breakToTheLeftOf: ['<div', '<p', '<table', '<tr', '<td', '<th', '<ul', '<ol', '<li', '<h1', '<h2', '<h3', '<h4', '<h5', '<h6'],
```

... so mostly block/table/list elements - that should theoretically help keep line lenghts consistent with the `lineLengthLimit` defined. Adding `<a` or `<span` there might break in some cases where inline elements rely on spaces.

> and I would guess it should be last

It does run last ([docs](https://maizzle.com/docs/build-process#compile-templates), point 7):

https://github.com/maizzle/framework/blob/772048fec423aa62b754cc2893aef06fa307a4e3/src/transformers/index.js#L21-L43

**Comment by bravecrayon** [comment]
@cossssmin Thanks for the write up!
