### ISSUE TITLE
Passing raw handlebars via content to component renders "undefined"

### ISSUE THREAD

**Issue by boylec** [maizzle/framework#891]
Lets say I have a component
```html
<div>
<content></content>
</div>
```

Then I use that component
```html
<component src="src/components/some-component.html">@{{Anything}}</component>
```

I would expect the build output to be
```html
<div>
@{{Anything}}
</div>
```

However, the build output is
```
<div>
undefined
</div>
```

Is this expected? Is there any way around it?

Note: raw blocks achieve the same result as @{{...}} but raw blocks having this effect in components appears to be documented while the documentation appear to suggest that @{{...}} should still work for components (not be undefined)

**Comment by cossssmin** [comment]
It's a bug in `v4.3.1`, due to the way components are rendered.

You'll need to "double ignore it" so to speak, like this:

```html
<component src="src/components/some-component.html">
  @@{{Anything}}
</component>
```

This will be fixed starting with `v4.4.0`, as we'll move to a new components system.

I've also [updated the `v4.3.1` docs](https://maizzle.com/docs/components#ignoring-expressions) so it's clearer until the next release, thanks!
